version: 2.1
orbs:
  node: circleci/node@2.1.1
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:24.16

commands:
  setup_snyk_user:
    steps:
      - run:
          name: Use snyk-main npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: Install dependencies
          command: npm install

jobs:
  security-scans:
    <<: *defaults
    resource_class: small
    steps:
      - checkout
      - setup_snyk_user
      - node/install-packages:
          override-ci: true
          cache-key: package.json
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    <<: *defaults
    steps:
      - checkout
      - setup_snyk_user
      - install_deps
      - node/install-packages:
          override-ci: true
          cache-key: package.json
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Install JUnit coverage reporter
          command: npm install --no-save jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: npx jest --coverage --ci --maxWorkers=3 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_snyk_user
      - install_deps
      - run:
          name: Release
          command: |
            export NPM_ID_TOKEN=$(circleci run oidc get --claims '{"aud": "npm:registry.npmjs.org"}')
            npx semantic-release@25.0.5

workflows:
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-vuln-alerts-sca
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          context:
            - open_source-managed
            - nodejs-install
          filters:
            branches:
              ignore:
                - master

      - test:
          name: Test
          context: nodejs-install

      - release:
          name: Release
          context:
            - nodejs-install
            - github-release
          requires:
            - Test
          filters:
            branches:
              only:
                - master
