version: 2.1
orbs:
  node: circleci/node@2.1.1
  prodsec: snyk/prodsec-orb@1

defaults: &defaults
  resource_class: small
  docker:
    - image: cimg/node:20.14

commands:
  setup_snyk_user:
    steps:
      - run:
          name: Use snyk-main npmjs user
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> .npmrc

jobs:
  security-scans:
    <<: *defaults
    resource_class: small
    steps:
      - checkout
      - setup_snyk_user
      - node/install-packages:
          override-ci: true
          cache-key: package.json
      - prodsec/security_scans:
          mode: auto
          release-branch: master
          open-source-additional-arguments: --exclude=test
          iac-scan: disabled

  test:
    <<: *defaults
    steps:
      - checkout
      - setup_snyk_user
      - node/install-packages:
          override-ci: true
          cache-key: package.json
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Install JUnit coverage reporter
          command: npm install --no-save jest-junit
      - run:
          name: Run tests with JUnit as reporter
          command: npx jest --coverage --ci --maxWorkers=3 --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT_DIR: ./reports/junit/
      - store_test_results:
          path: ./reports/junit/
      - store_artifacts:
          path: ./reports/junit
  release:
    <<: *defaults
    steps:
      - checkout
      - setup_snyk_user
      - node/install-packages:
          override-ci: true
          cache-key: package.json
      - run:
          name: Npm Build
          command: npm run build
      - run:
          name: Release on GitHub
          command: npx semantic-release@16

workflows:
  version: 2
  test:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: os-team-managed-alerts
          filters:
            branches:
              ignore:
                - master

      - security-scans:
          name: Security Scans
          context:
            - open_source-managed
            - nodejs-install
          filters:
            branches:
              ignore:
                - master

      - test:
          name: Test
          context: nodejs-install
          filters:
            branches:
              ignore:
                - master
  release:
    jobs:
      - security-scans:
          name: Security Scans
          context: open_source-managed
          filters:
            branches:
              only:
                - master

      - release:
          name: Release
          context: nodejs-lib-release
          filters:
            branches:
              only:
                - master
